CacheSyncinatorWorker:
  cron: "*/5 * * * *"
  class: "CacheSyncinatorWorker"
  queue: default

CacheSyncinatorUnfinishedWorker:
  cron: "*/5 * * * *"
  class: "CacheSyncinatorUnfinishedWorker"
  queue: default
