app:
  name: Accounts
  host: apps.biola.edu
  relative_url_root: /accounts

secret_token: # set in settings.local.yml

google_syncinator:
  scheme: http
  host: google-syncinator.dev
  port:
  script_name:
  version: v1
  access_id: # set in settings.local.yml
  secret_key: # set in settings.local.yml

urn_namespaces:
- "urn:biola:apps:three-keepers:"
- "urn:biola:apps:all:"

cas:
  url: "https://login.biola.edu/cas"

email:
  enabled: true
  from: no-reply@biola.edu
  developer: appdev@biola.edu
  smtp:
    server: postfix.biola.edu

views:
  photos:
    max_height: 150

page:
  per: 20

sentry:
  url: # Set in settings.local.yml
